### ISSUE TITLE
バリデーションとエラー表示機能の整理

### ISSUE THREAD

**Issue by kjirou** [kjirou/si_of_sis#56]
### TODO
- [x] validator.js を入れる
- [x] lib/validator を作る 
  - validator.extend をする場所と初期エラーメッセージ
  - 最小単位のバリデーションを定義する場所になる
- [x] エラー書式クラスを作る
  - [x] インスタンス同士をマージできるようにする
- [x] FormとField単位でバリデータを作る
- [x] User の作成/更新処理へ反映する
  - [x] logics を作るのも同時に行う
### 検討過程
- mongoose-validator はあまり必要ではない
  - validator.js の枠組み外の検証を増やせない、そもそも入れても書式が整うだけしか機能ない
  - その書式を尊重するほどのメジャーさはない
- i18n は最後に適用するので問題無さそう、このチケットでは考慮しない
- mongoose 側との共通化は、薄く行うだけで良い
  - mongoose 元機能を優先する, required とか enum とか
  - 足りない検証の場合に、Schema の validate 内で validator を呼ぶ程度
  - ユーザー側に表示が必要なエラーメッセージは設定しない
- Form Validator みたいなものが必要
  - バリデーションの組み合わせ/例外のバリデーション/初期エラメッセージ をまとめるもの
  - express-validator はダメ過ぎるので問題外
